name = "fraction_verification"
version = "0.1.0"
defaultTargets = ["FractionVerification"]

[[require]]
name = "corelib_verification"
git = "https://github.com/lindy-labs/corelib_verification.git"
rev = "main"

[[lean_lib]]
name = "FractionVerification"
