[package]
name = "fraction_verification"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.11.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[cairo]
inlining-strategy = "avoid"

[dependencies]

[dev-dependencies]
cairo_test = "2.11.4"

[lib]
sierra-text = true

[profile.fv]
sierra-replace-ids = true
sierra-text = true
