[package]
name = "fraction_verification"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.7.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]

[dev-dependencies]
cairo_test = "2.7.1"

[lib]
sierra-text = true

[profile.fv]
sierra-replace-ids = true
sierra-text = true
inlining-strategy = "avoid"
